FROM julia:1.8.5
MAINTAINER Leonardo Loures <luvres@hotmail.com>

RUN \
  julia -e '\
    using Pkg;\
    Pkg.add("JuMP");\
    Pkg.add("Gurobi")' \
  \  
  && tar zcf /opt/julia.tar.gz $HOME/.julia

